# Site
name: "Qauland's Sandbox"
description: 'Bukan sebuah kotak pasir yang indah.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'qauland@vivaldi.net'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Sal
      nickname:       sal
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    qauland:
      name:           Qauland
      nickname:       qauland
      site:           https://qauland.github.io
      avatar:         assets/images/avatar3.jpg
      bio:            "Pemilik situs ini. Sedang menjalani kehidupan sehari-harinya sebagai seorang mahasiswa."
      email:          ktbstsn@outlook.co.id
      twitter:        https://twitter.com/qauland

    hyropk:
      name:           Hiro Pakapuka
      nickname:       hyropk
      avatar:         assets/images/avatar2.jpg
      bio:            "Alternating... Zzz"
      email:          hiropakapuka@yahoo.co.id
      facebook:       https://fb.me/hyropk
      instagram:      https://instagram.com/8ch.pi

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: qauland
      avatar: assets/images/avatar3.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [Gemfile, Gemfile.lock, README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
